<?php

/**
 * @file
 * This defines all hooks used in this module.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_ENTITY_TYPE_presave() for nodes.
 */
function movie_type_node_presave(NodeInterface $node) {
  if ($node->getType() === 'movie_type') {
    $alias = '/movie/' . $node->label();
    $node->set('path', ['alias' => $alias]);
  }
}

/**
 * Implements hook_page_attachments().
 */
function movie_type_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'movie_type/movie-budget';
}

/**
 * Implements hook_theme().
 */
function movie_type_theme($existing, $type, $theme, $path) {
  return [
    'movie_budget' => [
      'variables' => [
        'budget' => NULL,
      ],
    ],
  ];

}
