<?php

/**
 * @file
 * This module alters the first config form we created.
 */

/**
 * Implements config_form_one_alteration_form_FORM_ID_alter().
 */
function config_form_one_alteration_form_config_form_one_admin_settings_alter(&$form) {
  $form['color'] = [
    '#type' => 'color',
    '#title' => 'Color',
    '#default_value' => '#ffffff',
    '#required' => TRUE,
  ];
  $form['message']['#title'] = t('(Altered) "Your" Message');
  $form['fullName']['#title'] = t('Enter YOUR Full Name');
  $form['actions']['submit']['#submit'][] = 'config_form_one_alter_submit_callback';
  return $form;
}

function config_form_one_alter_submit_callback(&$form, &$form_state) {
  $color = $form_state->getValue('color');
  $config = \Drupal::configFactory()->getEditable('config_form_one.admin_settings');
  $config
    ->set('color', $color);
  $config->save();
}
