<?php

/**
 * @file
 * This module alters the form.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function config_form_one_alteration_form_config_form_one_admin_settings_alter(&$form) {
  $form['color'] = [
    '#type' => 'color',
    '#title' => 'Color',
    '#default_value' => '#ffffff',
    '#required' => TRUE,
  ];
  $form['message']['#title'] = t('(Altered) "Your" Message');
  $form['fullName']['#title'] = t('Enter YOUR Full Name');
}
