<?php

/**
 * @file
 * This defines all hooks used in this module.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_ENTITY_TYPE_presave() for nodes.
 */
function dbt_one_node_presave(NodeInterface $node) {
  if ($node->getType() === 'dbt_one') {
    $alias = '/events/' . $node->label();
    $node->set('path', ['alias' => $alias]);
  }
}

/**
 * Implements hook_page_attachments().
 */
function dbt_one_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'dbt_one/events-dashboard';
}

/**
 * Implements hook_theme().
 */
function dbt_one_theme($existing, $type, $theme, $path) {
  return [
    'events_dashboard' => [
      'variables' => [
        'yearly' => NULL,
        'quarterly' => NULL,
        'types' => NULL,
      ],
    ],
  ];

}
